const T={
 balanced:{positive:"We sincerely thank the reviewer for this positive assessment of our manuscript and for recognizing its potential contribution.",theoretical:"We appreciate the reviewer’s important observation regarding the theoretical positioning and contribution of the study. In response, the relevant sections of the manuscript have been revised and strengthened accordingly.",literature:"We thank the reviewer for this helpful suggestion regarding the literature review. Accordingly, the relevant section has been updated and expanded with recent and directly relevant studies.",hypothesis:"We appreciate the reviewer’s insightful comment regarding the theoretical development of the hypotheses. In response, the rationale underlying the proposed relationships has been strengthened and elaborated.",method:"We thank the reviewer for pointing out the need for greater methodological transparency. Additional information has been incorporated into the methodology section to clarify the relevant procedures and decisions.",analytics:"We appreciate the reviewer’s request for further clarification regarding the analytical approach. In response, the rationale for the selected analytical method and its suitability for the research model have been explained in greater detail.",validity:"We thank the reviewer for emphasizing the importance of validity and reliability assessment. Accordingly, the relevant evaluations are now reported more explicitly and systematically.",discussion:"We thank the reviewer for this constructive suggestion concerning the discussion section. The relevant discussion has been revised to improve clarity and to distinguish the study’s contributions, implications, limitations, and future research directions more clearly.",general:"We thank the reviewer for this valuable and constructive comment. The concern has been carefully considered and the manuscript has been revised accordingly."},
 warm:{positive:"We are grateful to the reviewer for this encouraging assessment and for recognizing the potential contribution of our study.",theoretical:"We sincerely appreciate this insightful observation, which has helped us sharpen the theoretical positioning and contribution of the manuscript.",literature:"We sincerely thank the reviewer for this constructive suggestion. The literature review has been carefully updated and strengthened.",hypothesis:"We sincerely appreciate this insightful comment, which has helped us strengthen the theoretical logic underlying the proposed hypotheses.",method:"We sincerely appreciate the reviewer’s constructive methodological comment. The relevant procedures and methodological decisions have now been explained more transparently.",analytics:"We sincerely thank the reviewer for raising this important methodological point. The revised manuscript now provides a clearer justification for the analytical approach.",validity:"We sincerely appreciate this important observation. The validity and reliability assessments have been reported more comprehensively.",discussion:"We sincerely appreciate this helpful suggestion. The discussion has been carefully restructured and clarified in the revised manuscript.",general:"We sincerely appreciate the reviewer’s thoughtful and constructive comment. This suggestion has been carefully considered and addressed in the revised manuscript."},
 concise:{positive:"We thank the reviewer for this positive assessment of the manuscript.",theoretical:"We thank the reviewer for this comment. The theoretical contribution and positioning have been clarified.",literature:"We thank the reviewer for this suggestion. The literature review has been updated.",hypothesis:"We thank the reviewer for this comment. The theoretical rationale for the hypotheses has been strengthened.",method:"We thank the reviewer for this methodological comment. Additional methodological details have been added.",analytics:"We thank the reviewer for this comment. The analytical approach has been justified more clearly.",validity:"We thank the reviewer for this comment. The validity and reliability assessments have been clarified.",discussion:"We thank the reviewer for this suggestion. The discussion section has been revised accordingly.",general:"We thank the reviewer for this comment. The manuscript has been revised accordingly."}
};
function cls(t){t=t.toLowerCase();if(/timely|relevant topic|potential contribution|useful contribution|positive assessment/.test(t))return'positive';if(/theoretical contribution|theoretical framework|research gap|novelty|extends existing|positioning/.test(t))return'theoretical';if(/literature review|recent studies|references|2023|2024|2025|2026/.test(t))return'literature';if(/hypotheses|hypothesis|theoretical rationale|rationale underlying/.test(t))return'hypothesis';if(/validity|reliability|htmt|ave|cronbach/.test(t))return'validity';if(/analytical|analysis method|pls-sem|cb-sem|research model/.test(t))return'analytics';if(/discussion|managerial implications|limitations|future research|practical implications/.test(t))return'discussion';if(/methodology|sampling|data collection|measurement scales|sample characteristics|research design/.test(t))return'method';return'general'}
function n(s){return s.replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim()}
function splitSentences(text){return n(text).split(/(?<=[.!?])\s+(?=[A-Z])/).map(n).filter(Boolean)}
const actionWords='updating|strengthening|providing|clarifying|explaining|improving|revising|adding|expanding|including|reporting|discussing|distinguishing|reorganizing|positioning|justifying|articulating|elaborating|addressing|incorporating';
function listItems(s){s=n(s).replace(/[.;]$/,'');return s.split(/\s*,\s*|\s*,?\s+and\s+/i).map(x=>n(x.replace(/^and\s+/i,''))).filter(Boolean)}
function expandTopicList(sentence){
 let m=sentence.match(/^(.*?\b(?:regarding|concerning)\s+)(the\s+)?(.+?)([.?!])?$/i);
 if(m){const items=listItems(m[3]);if(items.length>=3)return items.map(x=>n(m[1]+(m[2]||'')+x+'.'))}
 m=sentence.match(/^(.*?\bdiscussion\s+of\s+)(.+?)([.?!])?$/i);
 if(m){const items=listItems(m[2]);if(items.length>=2)return items.map(x=>n(m[1]+x+'.'))}
 return[sentence]
}
function splitActionSentence(sentence){
 const m=sentence.match(/^(.*?\b(?:recommends?|suggests?|requests?|asks\s+for|calls\s+for)\s+)(.+?)([.?!])?$/i);if(!m)return expandTopicList(sentence);
 const lead=n(m[1]),rest=n(m[2]),rx=new RegExp('\\b('+actionWords+')\\b','ig'),hits=[...rest.matchAll(rx)];
 if(hits.length<2||hits[0].index>10)return expandTopicList(sentence);
 const out=[];for(let i=0;i<hits.length;i++){const a=hits[i].index,b=i+1<hits.length?hits[i+1].index:rest.length;let seg=rest.slice(a,b).replace(/^[,;\s]+/,'').replace(/^(?:and|as well as)\s+/i,'').replace(/(?:,?\s+and)?[.;,\s]+$/i,'');if(seg)out.push(...expandTopicList(n(lead+' '+seg+'.')))}return out
}
function splitShouldClauses(sentence){if((sentence.match(/\bshould\b/gi)||[]).length<2)return[sentence];const parts=sentence.split(/,\s+(?=(?:and\s+)?(?:the\s+|greater\s+|further\s+|additional\s+)?[^,]{1,80}\bshould\b)/i).map(x=>n(x.replace(/^and\s+/i,''))).filter(Boolean);return parts.length>1?parts.map(x=>/[.!?]$/.test(x)?x:x+'.'):[sentence]}
function decomposeSentence(sentence){sentence=n(sentence.replace(/^[-•]\s*/,''));if(!sentence)return[];const out=[];for(const a of splitShouldClauses(sentence)){const normalized=/^(highlights?|raises?|notes?|recommends?|suggests?|requests?|emphasizes?|observes?|indicates?|considers?|acknowledges?)\b/i.test(a)?'The reviewer '+a:a;out.push(...splitActionSentence(normalized))}return out.map(n).filter(Boolean)}
function decomposeBlock(block){return splitSentences(block).flatMap(decomposeSentence)}
function parse(raw){
 raw=raw.trim().replace(/\r\n?/g,'\n').replace(/\*\*/g,'').replace(/^#{1,6}\s*/gm,'').replace(/\u00a0/g,' ');if(!raw)return[];
 const marker=/\b(?:Reviewer\s*#?\s*|R)(\d+)(?!\.\d)\b\s*[:.-]?\s*/gi,matches=[...raw.matchAll(marker)],cnt={},out=[];
 const stop=/(?:After carefully considering|After considering|Based on the reviewers|Therefore, the decision|Therefore, my decision|My decision is|Decision\s*:|Major Revision|Minor Revision|Reject(?:ed|ion)?|Accept(?:ed|ance)?|Please address all comments|When submitting the revised|We appreciate your interest|Sincerely[, ]|Dear Author\(s\))/i;
 function add(r,txt){const k=txt.search(stop);if(k>=0)txt=txt.slice(0,k);for(const b of txt.split(/\n\s*\n+/).map(n).filter(Boolean)){const ex=b.match(/^(?:R|Reviewer\s*)?(\d+)\.(\d+)\s*[:.)-]?\s*(.*)$/i);if(ex){const rr=+ex[1],nn=+ex[2];cnt[rr]=Math.max(cnt[rr]||0,nn);if(n(ex[3]))out.push({id:`R${rr}.${nn}`,reviewer:rr,text:n(ex[3])});continue}for(const sub of decomposeBlock(b)){cnt[r]=(cnt[r]||0)+1;out.push({id:`R${r}.${cnt[r]}`,reviewer:r,text:sub})}}}
 if(matches.length){for(let i=0;i<matches.length;i++){const r=+matches[i][1],a=matches[i].index+matches[i][0].length,b=i+1<matches.length?matches[i+1].index:raw.length;add(r,raw.slice(a,b))}}else add(1,raw);return out
}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
function editorLetter(){const author=n(document.getElementById('authorName').value)||'[Author Name]';const d=new Date(),date=String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear();return `${date}\n\nDear [Editor(s)],\n\nThank you for the opportunity to revise our manuscript. We sincerely appreciate the editor's and reviewers' constructive comments and suggestions, which have helped us improve the clarity, rigor, and overall contribution of the manuscript.\n\nBelow, we provide a point-by-point response to each reviewer comment. Each comment is reproduced first, followed by our corresponding response. The relevant revisions have been incorporated into the revised manuscript and highlighted for ease of reference.\n\nSincerely,\n${author}`}
function generate(){
 const items=parse(document.getElementById('comments').value),tone=document.getElementById('tone').value,root=document.getElementById('results'),incEditor=document.getElementById('includeEditor').checked,incComments=document.getElementById('includeComments').checked,incResponses=document.getElementById('includeResponses').checked;window.currentItems=items;
 const reviewers=[...new Set(items.map(x=>x.reviewer))];document.getElementById('parseStatus').textContent=items.length?`✓ Detected: ${reviewers.map(r=>'Reviewer '+r).join(', ')} • ${items.length} separate comments`:'No reviewer comments were detected.';
 if(!items.length&&!incEditor){root.className='empty';root.textContent='Please enter reviewer comments or an editorial decision letter.';return}
 root.className='';root.innerHTML='';
 if(incEditor){const h=document.createElement('div');h.className='section-title';h.textContent='Editor Letter';root.appendChild(h);const ta=document.createElement('textarea');ta.id='editorLetter';ta.className='editor-letter';ta.value=editorLetter();root.appendChild(ta)}
 let lastReviewer=null;items.forEach((it,i)=>{if(it.reviewer!==lastReviewer){const h=document.createElement('div');h.className='reviewer-title';h.textContent='Reviewer '+it.reviewer;root.appendChild(h);lastReviewer=it.reviewer}const c=cls(it.text),d=document.createElement('div');d.className='result';let html=`<div class="rhead"><div class="rtitle">${esc(it.id)} <span class="pill">${esc(c)}</span></div></div>`;if(incComments)html+=`<div class="comment">${esc(it.text)}</div>`;if(incResponses){const st=T[tone][c]||T[tone].general;html+=`<label>Response ${esc(it.id.slice(1))}</label><textarea class="starter" id="s${i}">${esc(st)}</textarea>`}d.innerHTML=html;root.appendChild(d)})
}
function textAll(){const items=window.currentItems||[],incEditor=document.getElementById('includeEditor').checked,incComments=document.getElementById('includeComments').checked,incResponses=document.getElementById('includeResponses').checked,parts=[];if(incEditor){const e=document.getElementById('editorLetter');parts.push(e?e.value:editorLetter())}let current=null;items.forEach((it,i)=>{if(it.reviewer!==current){parts.push('Reviewer '+it.reviewer);current=it.reviewer}let s=it.id;if(incComments)s+='\n'+it.text;if(incResponses){const ta=document.getElementById('s'+i);s+='\n\nResponse '+it.id.slice(1)+':\n'+(ta?ta.value:(T[document.getElementById('tone').value][cls(it.text)]||T[document.getElementById('tone').value].general))}parts.push(s)});return parts.join('\n\n')}
function copyAll(){navigator.clipboard.writeText(textAll())}
function downloadTxt(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([textAll()],{type:'text/plain;charset=utf-8'}));a.download='reviewer_responses.txt';a.click();URL.revokeObjectURL(a.href)}
function clearAll(){document.getElementById('comments').value='';document.getElementById('results').className='empty';document.getElementById('results').textContent='No output has been generated yet.';document.getElementById('parseStatus').textContent='';window.currentItems=[]}
function loadExample(){document.getElementById('comments').value=`Dear Author(s),\n\nYour manuscript has now been evaluated by two independent reviewers. Both reviewers acknowledge the relevance of the topic and recognize the potential contribution of the study. Reviewer 1 highlights the need to clarify the theoretical contribution of the study and to explain more explicitly how the proposed framework extends the existing literature. The reviewer also recommends updating the literature review with more recent studies, strengthening the theoretical rationale underlying the hypotheses, and providing additional methodological details regarding the sampling procedure, data collection process, measurement scales, and analytical approach. Further clarification regarding validity and reliability assessments is also requested. Reviewer 2 raises additional concerns regarding the positioning and interpretation of the study. In particular, the reviewer recommends providing a clearer explanation of the research gap and the novelty of the study, strengthening the justification for the conceptual model, and discussing the findings more closely in relation to the theoretical framework. The reviewer also suggests improving the discussion of managerial implications, limitations, and directions for future research. After carefully considering both reports, I believe that the manuscript has potential, but substantial revisions are required before a final decision can be made.`;generate()}